version: "3.8"

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: bulgaria
      MYSQL_USER: web_user
      MYSQL_PASSWORD: Password1
    volumes:
      - db_data:/var/lib/mysql
      - ./db_setup.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - swarm-net

  web:
    image: myphpapp:latest
    ports:
      - "8080:80"
    deploy:
      replicas: 3
    depends_on:
      - db
    networks:
      - swarm-net

volumes:
  db_data:

networks:
  swarm-net:
    external: true
